apiVersion: v1
kind: Service
metadata:
  name: guestbookv1
  labels:
    app: guestbookv1
spec:
  ports:
  - port: 3000
    targetPort: http-server
  selector:
    app: guestbookv1
  type: LoadBalancer
